import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/signin/navbar";
import { AuthContextProvider } from "@/content/auth-context";
import { Suspense } from "react";
import QueryProvider from "@/lib/query-provider";

export const metadata: Metadata = {
  title: "Transportation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logo.svg" type="image/x-icon" />
      </head>
      <body>
        <Suspense>
          <QueryProvider>
            <AuthContextProvider>
              <main className="bg-main w-full relative">
                <Navbar />
                <section className="">{children}</section>
              </main>
            </AuthContextProvider>
          </QueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
