import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/signin/navbar";

export const metadata: Metadata = {
  title: "Transportation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logo.svg" type="image/x-icon" />
      </head>
      <body>
        <main className="bg-main w-full relative">
          <Navbar />
          <section className="">{children}</section>
        </main>
      </body>
    </html>
  );
}
